<?php
$category = $this->category;
$title = sprintf('Catégorie %s', $category->getName());
$this->headTitle($title);
$articles = $this->article;
$first = count($articles) ? array_shift($articles) : null;
?>

<div class="container-content">
    <div class="p-liste col-sm-12 col-md-12 col-xs-12 actu-canvas news">
        <div class="block-interne">
            <div class="title header-title"><?php echo $title ?></div>
        
            <?php if ($first) : ?>
            <?php $picture = ($first->getImg()) ? $first->getImg() : '/img/default.png'; ?>
            <div class="col-md-12 col-xs-12 col-sm-12">
                <div class="pd5 border-style">
                    <a href="<?php echo $this->url('blog/view', ['alias' => $first->getAlias()]) ?>">
                        <img src="<?php echo $this->thumb($picture, '_thumb'); ?>" style="height: 250px" class="img-responsive">
                    </a>
                </div>
                <div class="actu-title pt10">
                    <a href="<?php echo $this->url('blog/view', ['alias' => $first->getAlias()]) ?>"><?php echo $first->getTitle() ?></a>
                </div>
                <div class="content-actu">
                    <span class="date-display"><?php echo $this->jqueryTimeAgo($first->getCreatedAt()) ?></span>
                    <a href="<?php echo $this->url('blog/view', ['alias' => $first->getAlias()]) ?>" class="more-block">
                        <span class="readmore"><?php echo $this->translate('Lire plus') ?></span>
                    </a>
                </div>
            </div>
            <?php endif ?>
        </div>
        
        <div id="placeholder">
        <?php echo $this->partial('mdjaman-blog/_partials/paginate/article.phtml', ['article' => $articles]); ?>
        </div>
        
        <div class="col-md-12 col-xs-12 col-sm-12 infinit-loader morebox" id="lastPostsLoader" data-page="article" data-url="<?php echo $this->url('blog/category', ['alias' => $category->getAlias()]) ?>">
            <button class="btn-more"><span><i class="fa fa-plus-square"></i> <?php echo $this->translate('Plus d\'articles') ?></span></button>
        </div>
    </div>
</div>
